### ISSUE TITLE
Live Page

### ISSUE THREAD

**Issue by JohannesMP** [anvaka/gauss-distribution#3]
Would be really neat if you could enable [github pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) for this repo to  allow us to view the live version of index.html at http://anvaka.github.io/gauss-distribution :)

**Comment by anvaka** [comment]
Thank you for the suggestion! I'm not very happy with performance of the approach implemented here, and don't want to frustrate people. 

I'm working on a faster version, which will be available within a week

**Comment by anvaka** [comment]
Here it is: https://anvaka.github.io/pixchart/?d=2&ignore=&link=https%3A%2F%2Fi.imgur.com%2Fiyf2bRA.png&theme=charcoal
